name: CI Voll Med

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configura JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Roda Docker Compose
        run: docker compose up -d

      - name: Executa testes unitários
        run: mvn -B verify

      - name: Gera relatório JaCoCo
        run: mvn jacoco:prepare-agent verify

      - name: Análise estática
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          mvn -B sonar:sonar
          -Dsonar.projectKey=MarcelloFranca616_VollMed-api
          -Dsonar.organization=marcellofranca616
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=$SONAR_TOKEN
